# Generated by Django 4.2.28 on 2026-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_friends_friendrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_diary_to_friends',
            field=models.BooleanField(default=False),
        ),
    ]
