# Generated by Django 4.2.28 on 2026-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories_per_100g', models.PositiveIntegerField()),
                ('proteins', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
